version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HTTP_ADDR=:8080
      - STORAGE_TYPE=postgres
      - DB_DSN=postgres://user:password@db:5432/postsdb?sslmode=disable
      - LOG_LEVEL=info
    depends_on:
      db:
        condition: service_healthy
    networks:
      - posts-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postsdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - posts-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  posts-network:
    driver: bridge
